# Generated by Django 5.1.2 on 2024-10-20 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project_facilities", "0001_initial"),
        ("user_facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
            ],
            options={
                "db_table": "payment_gateway",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["transaction_fee"],
                        name="payment_gat_transac_671f9c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("donation", "Donation"),
                            ("fee", "Fee"),
                            ("withdrawal", "Withdrawal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transaction_facilities.paymentgateway",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="project_facilities.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="user_facilities.customuser",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="project_facilities.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="user_facilities.customuser",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="donation",
                        to="transaction_facilities.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "donation",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("in review", "In Review"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="user_facilities.customuser",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="transaction_facilities.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "dispute",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user"], name="transaction_user_id_3c7b67_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["project"], name="transaction_project_ed763c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["date"], name="transaction_date_27f26b_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "date"], name="transaction_status_18bcae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["user"], name="donation_user_id_da255f_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["project"], name="donation_project_0239b6_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["transaction"], name="donation_transac_a8db47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["transaction"], name="dispute_transac_167e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["user"], name="dispute_user_id_82f56a_idx"),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["status", "created_at"], name="dispute_status_25c644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["created_at"], name="dispute_created_28cf19_idx"
            ),
        ),
    ]
