# Generated by Django 5.1.2 on 2024-10-20 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "db_table": "category",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=45)),
                ("description", models.TextField(max_length=10000)),
                (
                    "goal_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("project_image", models.BinaryField(blank=True, null=True)),
                ("tags", models.CharField(blank=True, max_length=500, null=True)),
                ("video_url", models.URLField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="projects",
                        to="project_facilities.category",
                    ),
                ),
            ],
            options={
                "db_table": "project",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("goal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="project_facilities.project",
                    ),
                ),
            ],
            options={
                "db_table": "milestone",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "follow_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_facilities.customuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="project_facilities.project",
                    ),
                ),
            ],
            options={
                "db_table": "follower",
                "managed": True,
                "indexes": [
                    models.Index(fields=["user"], name="follower_user_id_bab130_idx"),
                    models.Index(
                        fields=["project"], name="follower_project_18d468_idx"
                    ),
                    models.Index(
                        fields=["follow_date"], name="follower_follow__d26d6a_idx"
                    ),
                ],
                "unique_together": {("user", "project")},
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="user_facilities.customuser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="project_facilities.project",
                    ),
                ),
            ],
            options={
                "db_table": "comment",
                "managed": True,
                "indexes": [
                    models.Index(fields=["project"], name="comment_project_c89ac9_idx"),
                    models.Index(fields=["user"], name="comment_user_id_bdf487_idx"),
                    models.Index(fields=["date"], name="comment_date_fa4929_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=500)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="project_facilities.project",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to="user_facilities.customuser",
                    ),
                ),
            ],
            options={
                "db_table": "report",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["reported_by"], name="report_reporte_fd3e29_idx"
                    ),
                    models.Index(fields=["project"], name="report_project_132bc4_idx"),
                    models.Index(fields=["date"], name="report_date_1b3c13_idx"),
                    models.Index(
                        fields=["report_status"], name="report_report__c4799c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="project_facilities.project",
                    ),
                ),
            ],
            options={
                "db_table": "update",
                "managed": True,
                "indexes": [
                    models.Index(fields=["project"], name="update_project_0462d8_idx"),
                    models.Index(fields=["date"], name="update_date_ab4e58_idx"),
                ],
            },
        ),
    ]
