# Generated by Django 5.1.2 on 2024-10-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project_facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("total_donations", models.IntegerField(default=0)),
                (
                    "total_funds",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="project_facilities.project",
                    ),
                ),
            ],
            options={
                "db_table": "analytics",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["total_views"], name="analytics_total_v_895907_idx"
                    ),
                    models.Index(
                        fields=["total_funds", "total_donations"],
                        name="analytics_total_f_3b4068_idx",
                    ),
                ],
            },
        ),
    ]
