# Generated by Django 5.1.2 on 2024-10-20 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "language",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "db_table": "location",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["country"], name="location_country_8b0444_idx"
                    ),
                    models.Index(fields=["city"], name="location_city_5c7276_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_picture", models.TextField(blank=True, null=True)),
                ("bio", models.CharField(blank=True, max_length=10000, null=True)),
                (
                    "user_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("creator", "Creator"),
                            ("backer", "Backer"),
                            ("admin", "Admin"),
                        ],
                        default=None,
                        max_length=7,
                        null=True,
                    ),
                ),
                ("join_date", models.DateField()),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="user_facilities.language",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="user_facilities.location",
                    ),
                ),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
    ]
