# Generated by Django 5.1.2 on 2024-10-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project_facilities", "0001_initial"),
        ("user_facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=1000)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("donation", "Donation"),
                            ("project_update", "Project Update"),
                            ("reward", "Reward"),
                        ],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="project_facilities.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="user_facilities.customuser",
                    ),
                ),
            ],
            options={
                "db_table": "notification",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["user"], name="notificatio_user_id_3cbd6f_idx"
                    ),
                    models.Index(
                        fields=["project"], name="notificatio_project_b7cac0_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_db7ad3_idx"
                    ),
                ],
            },
        ),
    ]
